apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Dipava/gitops_argocd_cd_project.git
    targetRevision: main
#    path: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=false

    automated:
      selfHeal: false
      prune: false

